### ISSUE TITLE
Generate a manifest file with error

### ISSUE THREAD

**Issue by Farhad2015** [tqcenglish/CSipSimple#6]
Hi, 
I am trying to build your project there when it build it give a 'debug/AndroidManifest.xml' and it appears some error like below image: 

<img width="1526" alt="screen shot 2017-12-14 at 1 23 03 pm" src="https://user-images.githubusercontent.com/10769565/33980303-846492b0-e0d2-11e7-9f43-9fdcd06f4cd9.png">

how can i solve it?

**Comment by tqcenglish** [comment]
degrade **gradle** version.

**Comment by rdantasnunes** [comment]
Hi,

   Tonight (here in Brazil) I try build and then give you a feedback.

best regards,

----
Rodrigo Dantas Nunes
http://www.linkedin.com/in/rdantasnunes
http://lattes.cnpq.br/5868835072659556

"A responsabilidade é uma atitude mental de não esperar que venha de fora


*a solução para o problema, mas contar consigo mesmo e com a sua
atuação para a resolução das situações que se criarem." Djalma D. P. R.
Oliveira, 200*5
P *Antes de imprimir, pense em sua responsabilidade e compromisso com o
Meio Ambiente *

2017-12-14 5:28 GMT-02:00 Mahmudur Rahman <notifications@github.com>:

**Comment by Farhad2015** [comment]
@tqcenglish, when i am not change **classpath 'com.android.tools.build:gradle:2.3.1'** its build correctly but when i change to **build.gradle:3.0.1** it appear that problem.

**Comment by Farhad2015** [comment]
@rdantasnunes , Thank you for your feedback.

**Comment by Farhad2015** [comment]
@tqcenglish, I am humbly request you to update your code for gradle 3.0.1
